# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 644)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.heroPreferenceTab = QtWidgets.QWidget()
        self.heroPreferenceTab.setObjectName("heroPreferenceTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.heroPreferenceTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.heroPreferenceTable = QtWidgets.QTableView(self.heroPreferenceTab)
        self.heroPreferenceTable.setObjectName("heroPreferenceTable")
        self.horizontalLayout.addWidget(self.heroPreferenceTable)
        self.mainTabWidget.addTab(self.heroPreferenceTab, "")
        self.compositionBuilder = QtWidgets.QWidget()
        self.compositionBuilder.setObjectName("compositionBuilder")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.compositionBuilder)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.compositionBuilderVerticalLayout = QtWidgets.QVBoxLayout()
        self.compositionBuilderVerticalLayout.setObjectName("compositionBuilderVerticalLayout")
        self.lineupGroupBox = QtWidgets.QGroupBox(self.compositionBuilder)
        self.lineupGroupBox.setObjectName("lineupGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.lineupGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineupComboBox1 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox1.setObjectName("lineupComboBox1")
        self.horizontalLayout_3.addWidget(self.lineupComboBox1)
        self.lineupComboBox2 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox2.setObjectName("lineupComboBox2")
        self.horizontalLayout_3.addWidget(self.lineupComboBox2)
        self.lineupComboBox3 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox3.setObjectName("lineupComboBox3")
        self.horizontalLayout_3.addWidget(self.lineupComboBox3)
        self.lineupComboBox4 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox4.setObjectName("lineupComboBox4")
        self.horizontalLayout_3.addWidget(self.lineupComboBox4)
        self.lineupComboBox5 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox5.setObjectName("lineupComboBox5")
        self.horizontalLayout_3.addWidget(self.lineupComboBox5)
        self.lineupComboBox6 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox6.setObjectName("lineupComboBox6")
        self.horizontalLayout_3.addWidget(self.lineupComboBox6)
        self.compositionBuilderVerticalLayout.addWidget(self.lineupGroupBox)
        self.compositionGroupBox = QtWidgets.QGroupBox(self.compositionBuilder)
        self.compositionGroupBox.setObjectName("compositionGroupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.compositionGroupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.compositionComboBox1 = QtWidgets.QComboBox(self.compositionGroupBox)
        self.compositionComboBox1.setObjectName("compositionComboBox1")
        self.horizontalLayout_5.addWidget(self.compositionComboBox1)
        self.compositionComboBox2 = QtWidgets.QComboBox(self.compositionGroupBox)
        self.compositionComboBox2.setObjectName("compositionComboBox2")
        self.horizontalLayout_5.addWidget(self.compositionComboBox2)
        self.compositionComboBox3 = QtWidgets.QComboBox(self.compositionGroupBox)
        self.compositionComboBox3.setObjectName("compositionComboBox3")
        self.horizontalLayout_5.addWidget(self.compositionComboBox3)
        self.compositionComboBox4 = QtWidgets.QComboBox(self.compositionGroupBox)
        self.compositionComboBox4.setObjectName("compositionComboBox4")
        self.horizontalLayout_5.addWidget(self.compositionComboBox4)
        self.compositionComboBox5 = QtWidgets.QComboBox(self.compositionGroupBox)
        self.compositionComboBox5.setObjectName("compositionComboBox5")
        self.horizontalLayout_5.addWidget(self.compositionComboBox5)
        self.compositionComboBox6 = QtWidgets.QComboBox(self.compositionGroupBox)
        self.compositionComboBox6.setObjectName("compositionComboBox6")
        self.horizontalLayout_5.addWidget(self.compositionComboBox6)
        self.compositionBuilderVerticalLayout.addWidget(self.compositionGroupBox)
        self.picksGroupBox = QtWidgets.QGroupBox(self.compositionBuilder)
        self.picksGroupBox.setObjectName("picksGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.picksGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.picksVerticalLayout1 = QtWidgets.QVBoxLayout()
        self.picksVerticalLayout1.setObjectName("picksVerticalLayout1")
        self.picksHeroLabel1 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksHeroLabel1.setFont(font)
        self.picksHeroLabel1.setText("")
        self.picksHeroLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.picksHeroLabel1.setObjectName("picksHeroLabel1")
        self.picksVerticalLayout1.addWidget(self.picksHeroLabel1)
        self.picksPlayerLabel1 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksPlayerLabel1.setFont(font)
        self.picksPlayerLabel1.setText("")
        self.picksPlayerLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.picksPlayerLabel1.setObjectName("picksPlayerLabel1")
        self.picksVerticalLayout1.addWidget(self.picksPlayerLabel1)
        self.horizontalLayout_4.addLayout(self.picksVerticalLayout1)
        self.picksVerticalLayout2 = QtWidgets.QVBoxLayout()
        self.picksVerticalLayout2.setObjectName("picksVerticalLayout2")
        self.picksHeroLabel2 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksHeroLabel2.setFont(font)
        self.picksHeroLabel2.setText("")
        self.picksHeroLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.picksHeroLabel2.setObjectName("picksHeroLabel2")
        self.picksVerticalLayout2.addWidget(self.picksHeroLabel2)
        self.picksPlayerLabel2 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksPlayerLabel2.setFont(font)
        self.picksPlayerLabel2.setText("")
        self.picksPlayerLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.picksPlayerLabel2.setObjectName("picksPlayerLabel2")
        self.picksVerticalLayout2.addWidget(self.picksPlayerLabel2)
        self.horizontalLayout_4.addLayout(self.picksVerticalLayout2)
        self.picksVerticalLayout3 = QtWidgets.QVBoxLayout()
        self.picksVerticalLayout3.setObjectName("picksVerticalLayout3")
        self.picksHeroLabel3 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksHeroLabel3.setFont(font)
        self.picksHeroLabel3.setText("")
        self.picksHeroLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.picksHeroLabel3.setObjectName("picksHeroLabel3")
        self.picksVerticalLayout3.addWidget(self.picksHeroLabel3)
        self.picksPlayerLabel3 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksPlayerLabel3.setFont(font)
        self.picksPlayerLabel3.setText("")
        self.picksPlayerLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.picksPlayerLabel3.setObjectName("picksPlayerLabel3")
        self.picksVerticalLayout3.addWidget(self.picksPlayerLabel3)
        self.horizontalLayout_4.addLayout(self.picksVerticalLayout3)
        self.picksVerticalLayout4 = QtWidgets.QVBoxLayout()
        self.picksVerticalLayout4.setObjectName("picksVerticalLayout4")
        self.picksHeroLabel4 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksHeroLabel4.setFont(font)
        self.picksHeroLabel4.setText("")
        self.picksHeroLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.picksHeroLabel4.setObjectName("picksHeroLabel4")
        self.picksVerticalLayout4.addWidget(self.picksHeroLabel4)
        self.picksPlayerLabel4 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksPlayerLabel4.setFont(font)
        self.picksPlayerLabel4.setText("")
        self.picksPlayerLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.picksPlayerLabel4.setObjectName("picksPlayerLabel4")
        self.picksVerticalLayout4.addWidget(self.picksPlayerLabel4)
        self.horizontalLayout_4.addLayout(self.picksVerticalLayout4)
        self.picksVerticalLayout5 = QtWidgets.QVBoxLayout()
        self.picksVerticalLayout5.setObjectName("picksVerticalLayout5")
        self.picksHeroLabel5 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksHeroLabel5.setFont(font)
        self.picksHeroLabel5.setText("")
        self.picksHeroLabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.picksHeroLabel5.setObjectName("picksHeroLabel5")
        self.picksVerticalLayout5.addWidget(self.picksHeroLabel5)
        self.picksPlayerLabel5 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksPlayerLabel5.setFont(font)
        self.picksPlayerLabel5.setText("")
        self.picksPlayerLabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.picksPlayerLabel5.setObjectName("picksPlayerLabel5")
        self.picksVerticalLayout5.addWidget(self.picksPlayerLabel5)
        self.horizontalLayout_4.addLayout(self.picksVerticalLayout5)
        self.picksVerticalLayout6 = QtWidgets.QVBoxLayout()
        self.picksVerticalLayout6.setObjectName("picksVerticalLayout6")
        self.picksHeroLabel6 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksHeroLabel6.setFont(font)
        self.picksHeroLabel6.setText("")
        self.picksHeroLabel6.setAlignment(QtCore.Qt.AlignCenter)
        self.picksHeroLabel6.setObjectName("picksHeroLabel6")
        self.picksVerticalLayout6.addWidget(self.picksHeroLabel6)
        self.picksPlayerLabel6 = QtWidgets.QLabel(self.picksGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picksPlayerLabel6.setFont(font)
        self.picksPlayerLabel6.setText("")
        self.picksPlayerLabel6.setAlignment(QtCore.Qt.AlignCenter)
        self.picksPlayerLabel6.setObjectName("picksPlayerLabel6")
        self.picksVerticalLayout6.addWidget(self.picksPlayerLabel6)
        self.horizontalLayout_4.addLayout(self.picksVerticalLayout6)
        self.compositionBuilderVerticalLayout.addWidget(self.picksGroupBox)
        self.runButton = QtWidgets.QPushButton(self.compositionBuilder)
        self.runButton.setObjectName("runButton")
        self.compositionBuilderVerticalLayout.addWidget(self.runButton)
        self.horizontalLayout_2.addLayout(self.compositionBuilderVerticalLayout)
        self.mainTabWidget.addTab(self.compositionBuilder, "")
        self.gridLayout.addWidget(self.mainTabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.heroPreferenceTab), _translate("MainWindow", "Hero Preferences"))
        self.lineupGroupBox.setTitle(_translate("MainWindow", "Lineup"))
        self.compositionGroupBox.setTitle(_translate("MainWindow", "Composition"))
        self.picksGroupBox.setTitle(_translate("MainWindow", "Picks"))
        self.runButton.setText(_translate("MainWindow", "RUN"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.compositionBuilder), _translate("MainWindow", "Composition Builder"))

