# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.heroPreferenceTab = QtWidgets.QWidget()
        self.heroPreferenceTab.setObjectName("heroPreferenceTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.heroPreferenceTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.heroPreferenceTable = QtWidgets.QTableView(self.heroPreferenceTab)
        self.heroPreferenceTable.setObjectName("heroPreferenceTable")
        self.horizontalLayout.addWidget(self.heroPreferenceTable)
        self.mainTabWidget.addTab(self.heroPreferenceTab, "")
        self.compositionBuilder = QtWidgets.QWidget()
        self.compositionBuilder.setObjectName("compositionBuilder")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.compositionBuilder)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.compositionBuilderVerticalLayout = QtWidgets.QVBoxLayout()
        self.compositionBuilderVerticalLayout.setObjectName("compositionBuilderVerticalLayout")
        self.lineupGroupBox = QtWidgets.QGroupBox(self.compositionBuilder)
        self.lineupGroupBox.setObjectName("lineupGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.lineupGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineupComboBox1 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox1.setObjectName("lineupComboBox1")
        self.horizontalLayout_3.addWidget(self.lineupComboBox1)
        self.lineupComboBox2 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox2.setObjectName("lineupComboBox2")
        self.horizontalLayout_3.addWidget(self.lineupComboBox2)
        self.lineupComboBox3 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox3.setObjectName("lineupComboBox3")
        self.horizontalLayout_3.addWidget(self.lineupComboBox3)
        self.lineupComboBox4 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox4.setObjectName("lineupComboBox4")
        self.horizontalLayout_3.addWidget(self.lineupComboBox4)
        self.lineupComboBox5 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox5.setObjectName("lineupComboBox5")
        self.horizontalLayout_3.addWidget(self.lineupComboBox5)
        self.lineupComboBox6 = QtWidgets.QComboBox(self.lineupGroupBox)
        self.lineupComboBox6.setObjectName("lineupComboBox6")
        self.horizontalLayout_3.addWidget(self.lineupComboBox6)
        self.compositionBuilderVerticalLayout.addWidget(self.lineupGroupBox)
        self.compositionGroupBox = QtWidgets.QGroupBox(self.compositionBuilder)
        self.compositionGroupBox.setObjectName("compositionGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.compositionGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.compositionVerticalLayout1 = QtWidgets.QVBoxLayout()
        self.compositionVerticalLayout1.setObjectName("compositionVerticalLayout1")
        self.compositionComboBox1 = QtWidgets.QComboBox(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compositionComboBox1.sizePolicy().hasHeightForWidth())
        self.compositionComboBox1.setSizePolicy(sizePolicy)
        self.compositionComboBox1.setObjectName("compositionComboBox1")
        self.compositionVerticalLayout1.addWidget(self.compositionComboBox1)
        self.heroGraphicsHorizontalLayout1 = QtWidgets.QHBoxLayout()
        self.heroGraphicsHorizontalLayout1.setObjectName("heroGraphicsHorizontalLayout1")
        self.heroGraphicsView1 = QtWidgets.QGraphicsView(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heroGraphicsView1.sizePolicy().hasHeightForWidth())
        self.heroGraphicsView1.setSizePolicy(sizePolicy)
        self.heroGraphicsView1.setMinimumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView1.setMaximumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.heroGraphicsView1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.heroGraphicsView1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.heroGraphicsView1.setInteractive(False)
        self.heroGraphicsView1.setObjectName("heroGraphicsView1")
        self.heroGraphicsHorizontalLayout1.addWidget(self.heroGraphicsView1)
        self.compositionVerticalLayout1.addLayout(self.heroGraphicsHorizontalLayout1)
        self.playerPickLabel1 = QtWidgets.QLabel(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerPickLabel1.sizePolicy().hasHeightForWidth())
        self.playerPickLabel1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.playerPickLabel1.setFont(font)
        self.playerPickLabel1.setText("")
        self.playerPickLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.playerPickLabel1.setObjectName("playerPickLabel1")
        self.compositionVerticalLayout1.addWidget(self.playerPickLabel1)
        self.horizontalLayout_4.addLayout(self.compositionVerticalLayout1)
        self.compositionVerticalLayout2 = QtWidgets.QVBoxLayout()
        self.compositionVerticalLayout2.setObjectName("compositionVerticalLayout2")
        self.compositionComboBox2 = QtWidgets.QComboBox(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compositionComboBox2.sizePolicy().hasHeightForWidth())
        self.compositionComboBox2.setSizePolicy(sizePolicy)
        self.compositionComboBox2.setObjectName("compositionComboBox2")
        self.compositionVerticalLayout2.addWidget(self.compositionComboBox2)
        self.heroGraphicsHorizontalLayout2 = QtWidgets.QHBoxLayout()
        self.heroGraphicsHorizontalLayout2.setObjectName("heroGraphicsHorizontalLayout2")
        self.heroGraphicsView2 = QtWidgets.QGraphicsView(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heroGraphicsView2.sizePolicy().hasHeightForWidth())
        self.heroGraphicsView2.setSizePolicy(sizePolicy)
        self.heroGraphicsView2.setMinimumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView2.setMaximumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.heroGraphicsView2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView2.setInteractive(False)
        self.heroGraphicsView2.setObjectName("heroGraphicsView2")
        self.heroGraphicsHorizontalLayout2.addWidget(self.heroGraphicsView2)
        self.compositionVerticalLayout2.addLayout(self.heroGraphicsHorizontalLayout2)
        self.playerPickLabel2 = QtWidgets.QLabel(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerPickLabel2.sizePolicy().hasHeightForWidth())
        self.playerPickLabel2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.playerPickLabel2.setFont(font)
        self.playerPickLabel2.setText("")
        self.playerPickLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.playerPickLabel2.setObjectName("playerPickLabel2")
        self.compositionVerticalLayout2.addWidget(self.playerPickLabel2)
        self.horizontalLayout_4.addLayout(self.compositionVerticalLayout2)
        self.compositionVerticalLayout3 = QtWidgets.QVBoxLayout()
        self.compositionVerticalLayout3.setObjectName("compositionVerticalLayout3")
        self.compositionComboBox3 = QtWidgets.QComboBox(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compositionComboBox3.sizePolicy().hasHeightForWidth())
        self.compositionComboBox3.setSizePolicy(sizePolicy)
        self.compositionComboBox3.setObjectName("compositionComboBox3")
        self.compositionVerticalLayout3.addWidget(self.compositionComboBox3)
        self.heroGraphicsHorizontalLayout3 = QtWidgets.QHBoxLayout()
        self.heroGraphicsHorizontalLayout3.setObjectName("heroGraphicsHorizontalLayout3")
        self.heroGraphicsView3 = QtWidgets.QGraphicsView(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heroGraphicsView3.sizePolicy().hasHeightForWidth())
        self.heroGraphicsView3.setSizePolicy(sizePolicy)
        self.heroGraphicsView3.setMinimumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView3.setMaximumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView3.setInteractive(False)
        self.heroGraphicsView3.setObjectName("heroGraphicsView3")
        self.heroGraphicsHorizontalLayout3.addWidget(self.heroGraphicsView3)
        self.compositionVerticalLayout3.addLayout(self.heroGraphicsHorizontalLayout3)
        self.playerPickLabel3 = QtWidgets.QLabel(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerPickLabel3.sizePolicy().hasHeightForWidth())
        self.playerPickLabel3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.playerPickLabel3.setFont(font)
        self.playerPickLabel3.setText("")
        self.playerPickLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.playerPickLabel3.setObjectName("playerPickLabel3")
        self.compositionVerticalLayout3.addWidget(self.playerPickLabel3)
        self.horizontalLayout_4.addLayout(self.compositionVerticalLayout3)
        self.compositionVerticalLayout4 = QtWidgets.QVBoxLayout()
        self.compositionVerticalLayout4.setObjectName("compositionVerticalLayout4")
        self.compositionComboBox4 = QtWidgets.QComboBox(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compositionComboBox4.sizePolicy().hasHeightForWidth())
        self.compositionComboBox4.setSizePolicy(sizePolicy)
        self.compositionComboBox4.setObjectName("compositionComboBox4")
        self.compositionVerticalLayout4.addWidget(self.compositionComboBox4)
        self.heroGraphicsHorizontalLayout4 = QtWidgets.QHBoxLayout()
        self.heroGraphicsHorizontalLayout4.setObjectName("heroGraphicsHorizontalLayout4")
        self.heroGraphicsView4 = QtWidgets.QGraphicsView(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heroGraphicsView4.sizePolicy().hasHeightForWidth())
        self.heroGraphicsView4.setSizePolicy(sizePolicy)
        self.heroGraphicsView4.setMinimumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView4.setMaximumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.heroGraphicsView4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView4.setInteractive(False)
        self.heroGraphicsView4.setObjectName("heroGraphicsView4")
        self.heroGraphicsHorizontalLayout4.addWidget(self.heroGraphicsView4)
        self.compositionVerticalLayout4.addLayout(self.heroGraphicsHorizontalLayout4)
        self.playerPickLabel4 = QtWidgets.QLabel(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerPickLabel4.sizePolicy().hasHeightForWidth())
        self.playerPickLabel4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.playerPickLabel4.setFont(font)
        self.playerPickLabel4.setText("")
        self.playerPickLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.playerPickLabel4.setObjectName("playerPickLabel4")
        self.compositionVerticalLayout4.addWidget(self.playerPickLabel4)
        self.horizontalLayout_4.addLayout(self.compositionVerticalLayout4)
        self.compositionVerticalLayout5 = QtWidgets.QVBoxLayout()
        self.compositionVerticalLayout5.setObjectName("compositionVerticalLayout5")
        self.compositionComboBox5 = QtWidgets.QComboBox(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compositionComboBox5.sizePolicy().hasHeightForWidth())
        self.compositionComboBox5.setSizePolicy(sizePolicy)
        self.compositionComboBox5.setObjectName("compositionComboBox5")
        self.compositionVerticalLayout5.addWidget(self.compositionComboBox5)
        self.heroGraphicsHorizontalLayout5 = QtWidgets.QHBoxLayout()
        self.heroGraphicsHorizontalLayout5.setObjectName("heroGraphicsHorizontalLayout5")
        self.heroGraphicsView5 = QtWidgets.QGraphicsView(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heroGraphicsView5.sizePolicy().hasHeightForWidth())
        self.heroGraphicsView5.setSizePolicy(sizePolicy)
        self.heroGraphicsView5.setMinimumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView5.setMaximumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.heroGraphicsView5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView5.setInteractive(False)
        self.heroGraphicsView5.setObjectName("heroGraphicsView5")
        self.heroGraphicsHorizontalLayout5.addWidget(self.heroGraphicsView5)
        self.compositionVerticalLayout5.addLayout(self.heroGraphicsHorizontalLayout5)
        self.playerPickLabel5 = QtWidgets.QLabel(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerPickLabel5.sizePolicy().hasHeightForWidth())
        self.playerPickLabel5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.playerPickLabel5.setFont(font)
        self.playerPickLabel5.setText("")
        self.playerPickLabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.playerPickLabel5.setObjectName("playerPickLabel5")
        self.compositionVerticalLayout5.addWidget(self.playerPickLabel5)
        self.horizontalLayout_4.addLayout(self.compositionVerticalLayout5)
        self.compositionVerticalLayout6 = QtWidgets.QVBoxLayout()
        self.compositionVerticalLayout6.setObjectName("compositionVerticalLayout6")
        self.compositionComboBox6 = QtWidgets.QComboBox(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compositionComboBox6.sizePolicy().hasHeightForWidth())
        self.compositionComboBox6.setSizePolicy(sizePolicy)
        self.compositionComboBox6.setObjectName("compositionComboBox6")
        self.compositionVerticalLayout6.addWidget(self.compositionComboBox6)
        self.heroGraphicsHorizontalLayout6 = QtWidgets.QHBoxLayout()
        self.heroGraphicsHorizontalLayout6.setObjectName("heroGraphicsHorizontalLayout6")
        self.heroGraphicsView6 = QtWidgets.QGraphicsView(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heroGraphicsView6.sizePolicy().hasHeightForWidth())
        self.heroGraphicsView6.setSizePolicy(sizePolicy)
        self.heroGraphicsView6.setMinimumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView6.setMaximumSize(QtCore.QSize(150, 180))
        self.heroGraphicsView6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.heroGraphicsView6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heroGraphicsView6.setInteractive(False)
        self.heroGraphicsView6.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.heroGraphicsView6.setObjectName("heroGraphicsView6")
        self.heroGraphicsHorizontalLayout6.addWidget(self.heroGraphicsView6)
        self.compositionVerticalLayout6.addLayout(self.heroGraphicsHorizontalLayout6)
        self.playerPickLabel6 = QtWidgets.QLabel(self.compositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerPickLabel6.sizePolicy().hasHeightForWidth())
        self.playerPickLabel6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.playerPickLabel6.setFont(font)
        self.playerPickLabel6.setText("")
        self.playerPickLabel6.setAlignment(QtCore.Qt.AlignCenter)
        self.playerPickLabel6.setObjectName("playerPickLabel6")
        self.compositionVerticalLayout6.addWidget(self.playerPickLabel6)
        self.horizontalLayout_4.addLayout(self.compositionVerticalLayout6)
        self.compositionBuilderVerticalLayout.addWidget(self.compositionGroupBox)
        self.heroPickTable = QtWidgets.QTableView(self.compositionBuilder)
        self.heroPickTable.setObjectName("heroPickTable")
        self.compositionBuilderVerticalLayout.addWidget(self.heroPickTable)
        self.horizontalLayout_2.addLayout(self.compositionBuilderVerticalLayout)
        self.mainTabWidget.addTab(self.compositionBuilder, "")
        self.gridLayout.addWidget(self.mainTabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.heroPreferenceTab), _translate("MainWindow", "Hero Preferences"))
        self.lineupGroupBox.setTitle(_translate("MainWindow", "Lineup"))
        self.compositionGroupBox.setTitle(_translate("MainWindow", "Composition"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.compositionBuilder), _translate("MainWindow", "Composition Builder"))

